.TH GNUNET\-FUSE 1 "2012\-06\-18" "0.9.3" "FUSE filesystem for GNUnet"

.SH NAME
gnunet\-fuse \- FUSE filesystem for GNUnet

.SH SYNOPSIS
\fBgnunet\-fuse\fR \-s \fIURI\fR [\-\- FUSE\-OPTIONS] \fIDIRECTORYNAME\fR
.PP
\fBgnunet\-fuse\fR \-\-help

.SH DESCRIPTION
gnunet\-fuse is the FUSE filesystem for GNUnet.
.PP
You need the URI of a file with the mime\-type of application/gnunet\-directory. You can either publish a directory with gnunet\-insert or do a search for the mime\-type. To mount the URI use the following command.
.PP
$ echo gnunet://ecrs/chk/XXXX/YYYY.NNNN > uri_file
.br
$ gnunet\-fuse \-s uri_file /mnt
.PP
Where gnunet://ecrs/chk/XXXX/YYYY.NNNN is the URI and /mnt is the mount point.

.SH OPTIONS
.IP "\-c, \-\-config=\fIFILE\fR" 4
use configuration file FILE.
.IP "\-d, \-\-directory=\fIPATH\fR" 4
path to your mountpoint.
.IP "\-h, \-\-help" 4
print this help.
.IP "\-L, \-\-log=\fILOGLEVEL\fR" 4
configure logging to use LOGLEVEL.
.IP "\-l, \-\-logfile=\fIFILE\fR" 4
configure logging to write logs to LOGFILE.
.IP "\-s, \-\-source=URI" 4
Source you get the URI from.
.IP "\-t, \-\-single\-threaded" 4
run in single-threaded mode.
.IP "\-v, \-\-version" 4
print the version number.

.SH SEE ALSO
\fIgnunet\fR(7)

.SH HOMEPAGE
More information about gnunet\-fuse and the GNUnet project can be found at <\fIhttp://www.gnunet.org/\fR>.
.PP
This manual page was written by Daniel Baumann <daniel.baumann@progress-technologies.net> and Bertrand Marc <beberking@gmail.com>.
